kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-helloworld-as3-configmap1
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
    "class": "AS3",
    "declaration": {
      "class": "ADC",
      "schemaVersion": "3.11.0",
      "id": "f5-hello-world-1",
      "label": "CIS AS3 Example",
      "remark": "Example of using CIS",
      "AS3": {
        "class": "Tenant",
        "MyApps": {
           "class": "Application",
           "template": "generic",
           "f5_hello_world_as3": {
              "class": "Service_TCP",
              "virtualAddresses": ["10.0.2.0/24"],
              "remark":"ingress: f5demo.tcp.v1",
              "virtualPort": 8080,
              "pool": "hello_demopool1"
           },
           "hello_demopool1": {
              "class": "Pool",
              "monitors": [ "tcp" ],
              "members": [{
                 "servicePort": 8080,
                 "serverAddresses": []
              }]
           }
        }
      }
    }
    }
