apiVersion: v1
kind: Service
metadata:
  name: f5-demo1-as3
  labels:
     cis.f5.com/as3-tenant: AS3
     cis.f5.com/as3-app: MyApps
     cis.f5.com/as3-pool: hello_demopool1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    run: f5-demo1-as3
